title: <p align="center"> Shruti Misra </p>
logo: "/images/prof_pic2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p align="center">
  <a href="https://www.linkedin.com/in/shrutim14/">LinkedIn</a> |
  <a href="https://github.com/shruti-misra">GitHub</a>
  </p>
  <p align="justify">
  I am a PhD student at the University of Washington with 5+ years of experience with interdisciplinary research. My research leverages mixed method (quantitative and qualitative) approaches to study innovation ecosystems in digital health and clean technologies. 
  <br><br>
  My expertise lies in integrating statistical analysis and visualization of heterogenous data with stakeholder interviews and surveys to identify, define and refine actionable insights that help drive business and social impact.  
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
